### ISSUE TITLE
How do you add pods/gems to the project?

### ISSUE THREAD

**Issue by glennfu** [HipByte/motion-game#11]
I tried to add: `gem 'afmotion'` to my Gemfile.

According to the AFMotion docs, the next step is to run `rake pod:install`

Unfortunately this fails with:

```
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'afmotion'.
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/Users/Glenn/RubymineProjects/Stinker/mobile/Rakefile:5:in `<top (required)>'
/Users/Glenn/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/Glenn/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
This file must be required within a RubyMotion project Rakefile.
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/motion-cocoapods-1.7.8/lib/motion/project/cocoapods.rb:26:in `<top (required)>'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/motion-cocoapods-1.7.8/lib/motion-cocoapods.rb:25:in `require'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/motion-cocoapods-1.7.8/lib/motion-cocoapods.rb:25:in `<top (required)>'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/afmotion-2.6/lib/afmotion.rb:2:in `require'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/afmotion-2.6/lib/afmotion.rb:2:in `<top (required)>'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/Users/Glenn/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/Users/Glenn/RubymineProjects/Stinker/mobile/Rakefile:5:in `<top (required)>'
/Users/Glenn/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/Glenn/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

Checking the source, "This file must be required within a RubyMotion project Makefile." spits out because `Motion::Project::Config` is not defined.

What can I do about this?

**Comment by glennfu** [comment]
I tried adding:

```
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
```
before `require 'bundler'` in my Rakefile. That got me a bit further. However then I get `uninitialized constant AFMotion (NameError)`. A closed issue on AFMotion's page suggests you need to add this to the project's `.setup` method:

```
  app.pods do
    pod 'AFNetworking', "~> 2.6.1"
  end
```

Doing so leads to this error: `NoMethodError: undefined method 'pods' for #<Motion::Project::IOSConfig:0x007fe2129243d8>`

Any ideas for me?

**Comment by glennfu** [comment]
OK, got it working. Rakefile looks like:

```
# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end
```

Gemfile looks like:
```
source 'https://rubygems.org'

gem 'rake'
gem 'motion-game', path: "~/RubymineProjects/motion-game"
gem 'motion-cocoapods'
gem 'motion-bundler'
gem 'afmotion'
```

ios.rb starts with:

```
# -*- coding: utf-8 -*-
require 'afmotion'

Motion::Project::App.setup do |app|
...
```

I also had to make sure and do `rm -rf vendor && rake clean && rake` to make sure the changes took. Hopefully if someone else has a similar problem this Issue will help them!
