### ISSUE TITLE
Failing to rake build:android

### ISSUE THREAD

**Issue by glennfu** [HipByte/motion-game#12]
Hello again!

I'm pretty sure I've gotten the Android setup working as I can use the 1.1 release to deploy my game to my Android device. However, when I try to build motion-game myself, after `rake build:setup` I run `rake build:android` and then see a ton of output ending with:

```
install -c /Users/Glenn/RubymineProjects/motion-game/ext/cocos2d-x/external/tiff/prebuilt/android/x86/libtiff.a /Users/Glenn/RubymineProjects/motion-game/build/android/x86/libtiff.a
mkdir -p /Users/Glenn/RubymineProjects/motion-game/build/android/x86
install -c /Users/Glenn/RubymineProjects/motion-game/ext/cocos2d-x/external/webp/prebuilt/android/x86/libwebp.a /Users/Glenn/RubymineProjects/motion-game/build/android/x86/libwebp.a
mkdir -p /Users/Glenn/RubymineProjects/motion-game/build/android/x86
install -c /Users/Glenn/RubymineProjects/motion-game/ext/cocos2d-x/external/zlib/prebuilt/android/x86/libz.a /Users/Glenn/RubymineProjects/motion-game/build/android/x86/libz.a
/Users/Glenn/.rubymotion-android/sdk/build-tools/22.0.1/aidl src/com/enhance/gameservice/IGameTuningService.aidl src/com/enhance/gameservice/IGameTuningService.java
/usr/bin/javac -cp "libs/android-async-http-1.4.8.jar" -d "/Users/Glenn/RubymineProjects/motion-game/build/android/classes" -bootclasspath "/Users/Glenn/.rubymotion-android/sdk/platforms/android-16/android.jar" src/com/chukong/cocosplay/client/CocosPlayClient.java src/com/enhance/gameservice/IGameTuningService.java src/org/cocos2dx/lib/Cocos2dxAccelerometer.java src/org/cocos2dx/lib/Cocos2dxActivity.java src/org/cocos2dx/lib/Cocos2dxBitmap.java src/org/cocos2dx/lib/Cocos2dxDownloader.java src/org/cocos2dx/lib/Cocos2dxEditBox.java src/org/cocos2dx/lib/Cocos2dxEditBoxHelper.java src/org/cocos2dx/lib/Cocos2dxGLSurfaceView.java src/org/cocos2dx/lib/Cocos2dxHandler.java src/org/cocos2dx/lib/Cocos2dxHelper.java src/org/cocos2dx/lib/Cocos2dxHttpURLConnection.java src/org/cocos2dx/lib/Cocos2dxJavascriptJavaBridge.java src/org/cocos2dx/lib/Cocos2dxLocalStorage.java src/org/cocos2dx/lib/Cocos2dxLuaJavaBridge.java src/org/cocos2dx/lib/Cocos2dxMusic.java src/org/cocos2dx/lib/Cocos2dxRenderer.java src/org/cocos2dx/lib/Cocos2dxSound.java src/org/cocos2dx/lib/Cocos2dxTextInputWraper.java src/org/cocos2dx/lib/Cocos2dxTypefaces.java src/org/cocos2dx/lib/Cocos2dxVideoHelper.java src/org/cocos2dx/lib/Cocos2dxVideoView.java src/org/cocos2dx/lib/Cocos2dxWebView.java src/org/cocos2dx/lib/Cocos2dxWebViewHelper.java src/org/cocos2dx/lib/GameControllerAdapter.java src/org/cocos2dx/lib/GameControllerDelegate.java src/org/cocos2dx/lib/GameControllerUtils.java src/org/cocos2dx/lib/ResizeLayout.java
Fatal Error: Unable to find package java.lang in classpath or bootclasspath
rake aborted!
Command failed with status (3): [/usr/bin/javac -cp "libs/android-async-htt...]
/Users/Glenn/RubymineProjects/motion-game/Rakefile:219:in `block in build_project'
/Users/Glenn/RubymineProjects/motion-game/Rakefile:207:in `chdir'
/Users/Glenn/RubymineProjects/motion-game/Rakefile:207:in `build_project'
/Users/Glenn/RubymineProjects/motion-game/Rakefile:236:in `block (2 levels) in <top (required)>'
/Users/Glenn/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/Glenn/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => build:android
(See full trace by running task with --trace)
```

Googling hasn't helped me with this error. Is there something you can suggest I try to get this to build?

**Comment by lrz** [comment]
Hi Glenn :)

What's your version of `javac`? In my environment I have the following:

```
$ javac -version
javac 1.7.0_71
```

You may want to try to install a recent Java (maybe this link will work: https://support.apple.com/kb/DL1572?locale=en_US)

**Comment by glennfu** [comment]
javac 1.8.0_65

**Comment by lrz** [comment]
Maybe it's the opposite problem, you are using a version too recent? Either way it looks like the problem could be fixed by replacing the `-bootclasspath "/Users/Glenn/.rubymotion-android/sdk/platforms/android-16/android.jar"` line with `-classpath <same-path>` and add a proper `-bootclasspath <path-to-jdk>` argument.

**Comment by glennfu** [comment]
It was a lot less boring than that. `motion android-setup` installed various versions of the SDK, but not Android 16. I had to manually install that one via the Android SDK Manager to get the version needed. Perhaps clarify in the Getting Started that this version is needed?

**Comment by glennfu** [comment]
OK, now `rake build:android` succeeds. Back in my game, I run `rake android:device` and get:

```
    Create build/android/Development-22/lib/x86/libpayload.so
    Create build/android/Development-22/lib/x86/gdbserver
    Create build/android/Development-22/lib/x86/gdb.setup
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
3 warnings
3 warnings
    Create build/android/Development-22/classes.dex

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:704)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
...while parsing com/chukong/cocosplay/client/CocosPlayClient.class

1 error; aborting
rake aborted!
Command failed with status (1): ["/Users/Glenn/.rubymotion-android/sdk/buil...]
/Library/RubyMotion/lib/motion/project/template/android.rb:546:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/android.rb:779:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/android.rb:779:in `each'
/Library/RubyMotion/lib/motion/project/template/android.rb:779:in `block in <top (required)>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

**Comment by Watson1978** [comment]
We added a patch of Java JDK 8 supporting and it will be shipped with next release.
