### ISSUE TITLE
Error running rake android:emulator

### ISSUE THREAD

**Issue by hugoerg56** [HipByte/motion-game#22]
```
   Compile /Users/hugorincon/motion-game/lib/motion-game/android/main_activity.rb
    Create build/android/Development-16/lib/x86/libpayload.so
    Create build/android/Development-16/lib/x86/gdbserver
    Create build/android/Development-16/lib/x86/gdb.setup
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
3 warnings
    Create build/android/Development-16/classes.dex

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:704)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
...while parsing com/chukong/cocosplay/client/CocosPlayClient.class

1 error; aborting
rake aborted!
```

**Comment by hugoerg56** [comment]
Looks like the problem was solved downgrading java to 1.6 was 1.8, now:

```
    Create build/android/Development-22/classes.dex
    Create build/android/Development-22/Hubble.apk
      Sign build/android/Development-22/Hubble.apk
     Align build/android/Development-22/Hubble.apk
   Install build/android/Development-22/Hubble.apk
    ERROR! Could not find emulator
```

where can I create a emulator?

**Comment by casper91** [comment]
For an emulator I would recommend [Genymotion](https://www.genymotion.com/), which is also recommended by RubyMotion them self.

**Comment by hugoerg56** [comment]
Genymotion running cool!
