### ISSUE TITLE
Build error with Android NDK r11 with motion-game v1.1.1

### ISSUE THREAD

**Issue by Watson1978** [HipByte/motion-game#25]
```
$ rake android:build
    Create build/android/Development-16/AndroidManifest.xml
    Create build/android/Development-16/motion-cocos.jar.bridgesupport
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
   Compile ./app/game_scene.rb
   Compile ./app/application.rb
   Compile /Users/watson/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/motion-game-1.1.1/lib/motion-game/android/main_activity.rb
    Create build/android/Development-16/lib/armeabi/libpayload.so
/Users/watson/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/motion-game-1.1.1/lib/motion-game/../../build/android/armeabi/libmotion-cocos.a(CCConsole.cpp.o):base/CCConsole.cpp:function cocos2d::Console::listenOnTCP(int): error: undefined reference to 'bzero'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
Command failed with status (1): [/Users/watson/.rubymotion-android/ndk/tool...]
/Library/RubyMotion/lib/motion/project/template/android.rb:357:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/android.rb:211:in `each'
/Library/RubyMotion/lib/motion/project/template/android.rb:211:in `block in <top (required)>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

**Comment by Watson1978** [comment]
Just need to release new version (v1.1.2) included https://github.com/HipByte/motion-game/commit/df1e2e7c91b32b24ab12b00b880ac48de500ce54 patch
