### ISSUE TITLE
Using constant without `MG::` will raise `uninitialized constant` exception

### ISSUE THREAD

**Issue by Watson1978** [HipByte/motion-game#66]
## Reproduce code
```
class HelloWorld < MG::Scene
  def initialize
    Repeat::FOREVER
  end
end
```

## Result
```
$ rake ios:simulator
...

2016-12-22 22:12:41.457 HelloWorld[24966:338379] hello_world.rb:3:in `initialize': uninitialized constant HelloWorld::Repeat (NameError)
	from application.rb:4:in `start'
	from app_delegate.rb:16:in `application:didFinishLaunchingWithOptions:'
2016-12-22 22:12:41.464 HelloWorld[24966:338379] *** Terminating app due to uncaught exception 'NameError', reason: 'hello_world.rb:3:in `initialize': uninitialized constant HelloWorld::Repeat (NameError)
	from application.rb:4:in `start'
	from app_delegate.rb:16:in `application:didFinishLaunchingWithOptions:'
```

**Comment by Watson1978** [comment]
To omit MG:: namespace, user defined class need to have MG:: namespace ..., like

```
module MG
  class HelloWorld < Scene
    def initialize
      Repeat::FOREVER
    end
  end
end
```
